# Generated by Django 4.1 on 2022-08-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Dc', 'Data Collection'), ('sl', 'Selection')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_shared_creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response_To_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_Type', models.CharField(blank=True, choices=[('placed', 'placed'), ('selected', 'selected')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_Response', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ViewdBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form')),
            ],
        ),
    ]
