# Generated by Django 4.1 on 2022-08-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewdby',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsefromuser',
            name='Form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
        migrations.AddField(
            model_name='responsefromuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response_to_user',
            name='Form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
        migrations.AddField(
            model_name='response_to_user',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_shared_creator',
            name='Form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
        migrations.AddField(
            model_name='form_shared_creator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='Visitng_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.visiting_company_record'),
        ),
    ]
