# Generated by Django 4.1 on 2022-08-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Form', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Type',
            field=models.CharField(blank=True, choices=[('Dc', 'Data Collection'), ('sl', 'Selection'), ('pl', 'placed')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Visitng_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.visiting_company_record'),
        ),
    ]
