# Generated by Django 4.1 on 2022-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_questions_additional_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Extract_from',
            field=models.TextField(default='[]'),
        ),
    ]
