# Generated by Django 4.1 on 2022-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_form_creator_note_delete_form_shared_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Type',
            field=models.CharField(blank=True, choices=[('Dc', 'Data Collection'), ('sl', 'Selection'), ('pl', 'Placement')], max_length=5, null=True),
        ),
    ]
