# Generated by Django 4.1 on 2022-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_alter_questions_extract_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='expire_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
