# Generated by Django 4.1 on 2022-09-10 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form', '0012_alter_form_expire_date_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response_to_user',
            unique_together={('Form_id', 'User', 'response_Type')},
        ),
    ]
