# Generated by Django 4.1 on 2022-08-19 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PostalCode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Invalid postal Code', regex='^[0-9]{6}|[0-9]{3}\\s[0-9]{3}$')]),
        ),
    ]
