# Generated by Django 4.1 on 2022-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_postalcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_all_student', 'access to view all student')]},
        ),
    ]
