# Generated by Django 4.1 on 2022-09-10 08:48

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='user',
            name='collage_joinig_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Parent_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Student_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='collage_passingYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.RegexValidator(code='invalid_username', message='Email does not belong to bvp.edu', regex='^[a-zA-Z0-9._%+-]+\\-coemumbai@bvp.edu.in$')]),
        ),
    ]
