# Generated by Django 4.1 on 2022-09-11 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_user_bio_user_collage_joinig_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImage', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
