# Generated by Django 4.1 on 2022-08-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_user_form',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
    ]
