# Generated by Django 4.1 on 2022-08-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Department', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_user_form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department_related_form',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department'),
        ),
        migrations.AddField(
            model_name='department_related_form',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
    ]
