# Generated by Django 4.1 on 2022-08-10 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Department', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific_user_form',
            name='user',
        ),
        migrations.AddField(
            model_name='specific_user_form',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
